name: nmap
base: core18
adopt-info: nmap
summary: A free and open source utility for network discovery and security auditing
description: |
  Nmap is a utility for network exploration or security auditing. It
  supports ping scanning (determine which hosts are up), many port
  scanning techniques, version detection (determine service protocols
  and application versions listening behind ports), and TCP/IP
  fingerprinting (remote host OS or device identification). Nmap also
  offers flexible target and port specification, decoy/stealth scanning,
  sunRPC scanning, and more. Most Unix and Windows platforms are
  supported in both GUI and commandline modes.

  Once installed, this snap needs manually connecting to some plugs:

     sudo snap connect nmap:network-control

  Main website: https://nmap.org/


grade: devel
confinement: strict
license: GPL-2.0
icon: meta/gui/icon.png
compression: lzo

apps:
    nmap:
        command: nmap
        environment:
            LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas"
        plugs: [network, network-bind, network-control, home]
    ncat:
        command: ncat
        plugs: [network, network-bind, network-control, home]
    nping:
        command: nping
        plugs: [network, network-bind, network-control]

parts:
    nmap:
        plugin: autotools
        configflags: [--prefix=$SNAPCRAFT_PART_INSTALL/usr]
        install-via: "prefix"
        source: https://github.com/nmap/nmap
        source-type: git
        source-branch: master
        override-pull: |
          snapcraftctl pull
          git -C $SNAPCRAFT_PART_SRC tag 7.91 9529327  # GitHub mirror has no tags or branches :(
          version="$(git tag)"
          snapcraftctl set-version "$version"
        build-packages: [liblinear-dev, liblua5.3-dev, libpcap0.8-dev, libpcre3-dev, libssh2-1-dev, libssl-dev, lua-lpeg-dev, zlib1g-dev]
        stage-packages: [liblinear3, liblua5.3-0, libpcap0.8, libpcre3, libssh2-1, libssl1.1, lua-lpeg, zlib1g]
